# Generated by Django 5.2.1 on 2025-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('спорт', 'Спорт'), ('ремонт', 'Ремонт'), ('техника', 'Техника'), ('кухня', 'Кухня'), ('автомобиль', 'Автомобиль'), ('другое', 'Другое')], max_length=100),
        ),
    ]
